spring.application.name=cafe-soluble-api

# Server Configuration
server.port=8080

# Database Configuration (PostgreSQL via Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/cafesoluble_db
spring.datasource.username=baxava
spring.datasource.password=medifind_baxava
spring.datasource.driver-class-name=org.postgresql.Driver
